<?php
/**
 * @file
 * Collect email addresses from a form within a node or block.
 */

/**
 * Implements hook_menu().
 */
function mailfish_menu() {
  $items = array();
  $items['admin/config/content/mailfish'] = array(
    'title' => 'MailFish Settings',
    'description' => 'Administer MailFish Settings.',
    'page callback' => 'mailfish_admin_settings_form_callback',
    'access arguments' => array('manage mailfish settings'),
    'file' => 'mailfish.admin.inc',
  );
  $items['admin/reports/mailfish'] = array(
    'title' => 'MailFish Signups',
    'description' => 'View MailFish Signups',
    'page callback' => 'mailfish_signups',
    'access arguments' => array('view mailfish subscriptions'),
    'file' => 'mailfish.admin.inc',
  );
  return $items;
}

/**
 * Implements hook_permission().
 */
function mailfish_permission() {
  $perm = array(
    'view mailfish subscriptions' => array(
      'title' => t('View Mailfish subscriptions'),
    ),  
    'create mailfish subscription' => array(
      'title' => t('Create Mailfish subscriptions'),
    ),  
    'manage mailfish settings' => array(
      'title' => t('Manage Mailfish settings'),
    )   
  );  
  return $perm;
}
