<?php
/**
 * @file
 * Collect email addresses from a form within a node or block.
 */

/**
 * Implements hook_menu().
 */
function mailfish_menu() {
  $items = array();
  $items['admin/config/content/mailfish'] = array(
    'title' => 'MailFish Settings',
    'description' => 'Administer MailFish Settings.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('mailfish_admin_settings_form'),
    'access arguments' => array('manage mailfish settings'),
    'file' => 'mailfish.admin.inc',
  );
  $items['admin/reports/mailfish'] = array(
    'title' => 'MailFish Signups',
    'description' => 'View MailFish Signups',
    'page callback' => 'mailfish_signups',
    'access arguments' => array('view mailfish subscriptions'),
    'file' => 'mailfish.admin.inc',
  );
  return $items;
}

/**
 * Menu Callback; Allows admins to pick which content types should be   enabled for signups.
 */
function mailfish_admin_settings_callback() {
  return drupal_get_form('mailfish_admin_settings_form');
}

/**
 * Implements hook_permission().
 */
function mailfish_permission() {
  $perm = array(
    'view mailfish subscriptions' => array(
      'title' => t('View Mailfish subscriptions'),
    ),  
    'create mailfish subscription' => array(
      'title' => t('Create Mailfish subscriptions'),
    ),  
    'manage mailfish settings' => array(
      'title' => t('Manage Mailfish settings'),
    )   
  );  
  return $perm;
}

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * Adds a checkbox to allow email address collection per node for
 * enabled content types.
 */
function mailfish_form_node_form_alter(&$form, $form_state) {
  $node = $form['#node'];
  // Perform our check to see if we should be performing an action as the very first action.
  $types = variable_get('mailfish_types', array());
  // Check if this node type is enabled for mailfish
  // and that the user has access to the per-node settings.
  if ($types[$node->type] && user_access('manage mailfish settings')) {
    // Add a new fieldset with a checkbox for per-node mailfish setting.
    $form['mailfish'] = array(
      '#title' => t('MailFish'),
      '#type' => 'fieldset',
      '#collapsible' => TRUE,
      '#collapsed' => FALSE,
      '#group' => 'additional_settings',
    );
    $form['mailfish']['mailfish_enabled'] = array(
      '#title' => t('Collect e-mail addresses for this node.'),
      '#type' => 'checkbox',
      '#default_value' => isset($node->mailfish_enabled) ? $node->mailfish_enabled : FALSE,
    );
  }
}