<?php
/**
 * @file
 * Collect email addresses from a form within a node or block.
 */

/**
 * Implements hook_menu().
 */
function mailfish_menu() {
  $items = array();
  $items['admin/config/content/mailfish'] = array(
    'title' => 'MailFish Settings',
    'description' => 'Administer MailFish Settings.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('mailfish_admin_settings_form'),
    'access arguments' => array('manage mailfish settings'),
    'file' => 'mailfish.admin.inc',
  );
  $items['admin/reports/mailfish'] = array(
    'title' => 'MailFish Signups',
    'description' => 'View MailFish Signups',
    'page callback' => 'mailfish_signups',
    'access arguments' => array('view mailfish subscriptions'),
    'file' => 'mailfish.admin.inc',
  );
  return $items;
}

/**
 * Menu Callback; Allows admins to pick which content types should be enabled for signups.
 */
function mailfish_admin_settings_callback() {
//Negi editing
return drupal_get_form('mailfish_admin_settings_form');
return ´Settings form should go here´ ;
}

/**
 * Implements hook_permission().
 */
function mailfish_permission() {
  $perm = array(
    'view mailfish subscriptions' => array(
      'title' => t('View Mailfish subscriptions'),
    ),  
    'create mailfish subscription' => array(
      'title' => t('Create Mailfish subscriptions'),
    ),  
    'manage mailfish settings' => array(
      'title' => t('Manage Mailfish settings'),
    )   
  );  
  return $perm;
}

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * Adds a checkbox to allow email address collection per node for
 * enabled content types.
 */
function mailfish_form_node_form_alter(&$form, $form_state) {
  $node = $form['#node'];
  // Perform our check to see if we should be performing an action as the very first action.
  $types = variable_get('mailfish_types', array());
  // Check if this node type is enabled for mailfish
  // and that the user has access to the per-node settings.
  if ($types[$node->type] && user_access('manage mailfish settings')) {
    // Add a new fieldset with a checkbox for per-node mailfish setting.
    $form['mailfish'] = array(
      '#title' => t('MailFish'),
      '#type' => 'fieldset',
      '#collapsible' => TRUE,
      '#collapsed' => FALSE,
      '#group' => 'additional_settings',
    );
    $form['mailfish']['mailfish_enabled'] = array(
      '#title' => t('Collect e-mail addresses for this node.'),
      '#type' => 'checkbox',
      '#default_value' => isset($node->mailfish_enabled) ? $node->mailfish_enabled : FALSE,
    );
  }
}

/**
 * Implements hook_node_view().
 */
function mailfish_node_view($node, $view_mode, $langcode) {
  $node->content['mailfish'] = array(
    '#markup' => drupal_render(drupal_get_form('mailfish_email_form', $node->nid)),
    '#weight' => 100,
  );
}

/**
 * Provide the form to add an email address.
 */
function mailfish_email_form($form, $form_state, $nid = 0) {
  global $user;
  $form['email'] = array(
    '#title' => t('Email address'),
    '#type' => 'textfield',
    '#size' => 20,
    '#description' => t('Join our mailing list'),
    '#default_value' => isset($user->mail) ? $user->mail : '',
  );

  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Sign Up'),
  );
  $form['nid'] = array(
    '#type' => 'hidden',
    '#value' => $nid,
  );
  return $form;
}

/**
 * Validation handler for mailfish_email_form.
 */
function mailfish_email_form_validate($form, &$form_state) {

  $email = $form_state['values']['email'];
  if (!$email) {
    form_set_error('email', t('You must provide an email address in order to join a mailing list.'));
  }
  elseif (!valid_email_address($email)) {
    $message = t('The address %email is not a valid email address. Please re-enter your address.', array('%email' => $email));
    form_set_error('email', $message);
  }

  $nid = isset($form_state['values']['nid']) ? $form_state['values']['nid'] : 0;
  if (!mailfish_get_node_enabled($nid) && $nid != 0) {
    form_set_error('', t('MailFish subscriptions are not available for this node.'));
  }

  // Do not allow multiple signups for the same node and email address.
  $previous_signup = db_query("SELECT mail FROM {mailfish} WHERE nid = :nid AND mail = :mail", array('nid' => $nid, 'mail' => $email))->fetchField();
  if ($previous_signup) {
    form_set_error('email', t('The address %email is already subscribed to this list.', array('%email' => $email)));
  }
}

/**
 * Submission handler for mailfish_email_form.
 */
function mailfish_email_form_submit($form, &$form_state) {
  // The sitewide signup form will not have a set $form['#node'].
  $nid = isset($form_state['values']['nid']) ? $form_state['values']['nid'] : 0;
  if ($nid) { // Comment: it might be a good idea to add an extra is_numeric($nid) check here

    $node = node_load($nid);
  }
  // The sitewide signup form will not have a title, retrieve and use the site's name.
  $title = isset($node) ? $node->title : variable_get('site_name', 'Drupal');

  // Signup the user.
  mailfish_signup($form_state['values']['email'], $nid);
  // Provide the user with a translated confirmation message.
  drupal_set_message(t('Thank you for joining the mailing list for %title. You have been added as %email.', array('%title' => $title, '%email' => $form_state['values']['email'])));
}


/**
 * Determine if a node is set to display an email address form.
 *
 * @param int $nid
 *   The node id of the node in question.
 *
 * @return boolean
 */
function mailfish_get_node_enabled($nid) {
  // @TODO: This function is just a stub.
  return TRUE;
}

/**
 * Store a mailfish email signup.
 */
function mailfish_signup($email, $nid, $account = NULL) {
  drupal_set_message(t('Pretending to signup %email to %nid', array('%email' => $email, '%nid' => $nid)));
}
